---
brew_taps:
  - domt4/autoupdate
  - homebrew/cask-versions
  - homebrew/cask-fonts
  - teamookla/speedtest
  - yt-dlp/taps

brew_packages:
  - ansible
  - awscli
  - bat
  - composer
  - coreutils
  - exa
  - exiftool
  - ffmpeg
  - git-extras
  - go
  - gpg2
  - htop
  - imapsync
  - iperf
  - jq
  - mas
  - nodejs
  - pinentry-mac
  - ruby
  - telnet
  - terminal-notifier
  - tmux
  - wget
  - yt-dlp
  - zplug
  - zsh
  - speedtest

cask_packages:
  - 1password
  - aerial
  - alfred
  - appcleaner
  - autodesk-fusion360
  - bartender
  - brave-browser
  - arc
  - figma
  - firefox
  - firefox-developer-edition
  - docker
  - font-hack-nerd-font
  - gas-mask
  - gitup
  - iterm2
  - keka
  - macdown
  - notion
  - prusaslicer
  - rectangle
  - slack
  - nordvpn
  - nvalt
  - qlmarkdown
  - qlstephen
  - quicklook-json
  - spotify
  - suspicious-package
  - telegram
  - transmit
  - vagrant
  - visual-studio-code

gem_packages:
  - nokogiri

mas_packages:
  - 408981434  # iMovie
  - 955848755  # Theine
  - 1351639930  # Gifski
  - 1568924476 # Mela

npm_packages:
  - bower
  - grunt
  - gulp
  - init.js
  - json
  - prettyjson
  - tlstools
  - yarn
  - yo

pip_packages:
  - beautifulsoup4
  - docker
  - ffpb
