- name: Set up local workstation
  hosts: local
  ignore_errors: yes
  roles:
    - role: brew
      tags:
        - brew
    - role: dotfiles
      tags:
        - dotfiles
    - role: npm
      tags:
        - npm
    - role: macos
      tags:
        - macos
    - role: pip
      tags:
        - pip
