brew_taps:
  - domt4/autoupdate
  - homebrew/cask-versions
  - homebrew/cask-fonts

brew_packages:
  - ansible
  - bat
  - exa
  - font-sauce-code-pro-nerd-font
  - git-extras
  - htop
  - jq
  - mas
  - nodejs
  - telnet
  - terminal-notifier
  - tmux
  - wget
  - zplug
  - zsh

cask_packages:
  - 1password
  - alfred
  - appcleaner
  - bartender
  - docker
  - gitup
  - google-chrome
  - iterm2
  - keka
  - macdown
  - nvalt
  - spotify
  - telegram
  - transmit
  - virtualbox
  - visual-studio-code

cask_ql_packages:
  - provisionql
  - qlcolorcode
  - qlimagesize
  - qlmarkdown
  - qlprettypatch
  - qlstephen
  - qlvideo
  - quicklook-csv
  - quicklook-json
  - suspicious-package
  - webpquicklook
